[package]
authors = ["Dragan Rakita <dragan0rakita@gmail.com>"]
edition = "2021"
name = "revme"
keywords = ["ethereum", "evm"]
license = "MIT"
repository = "https://github.com/bluealloy/revm"
description = "Rust Ethereum Virtual Machine Executable"
version = "0.2.0"

[dependencies]
hash-db = "0.15"
hashbrown = "0.14"
indicatif = "0.17"
plain_hasher = "0.2"
revm = { path = "../../crates/revm", version = "3.5.0", default-features = false, features = [
    "ethersdb",
    "std",
    "serde",
    "c-kzg",
] }
alloy-rlp = { version = "0.3", default-features = false, features = [
    "arrayvec", 
    "derive",
] }
serde = { version = "1.0", features = ["derive", "rc"] }
serde_json = { version = "1.0", features = ["preserve_order"] }
structopt = "0.3"
thiserror = "1.0"
triehash = "0.8"
walkdir = "2.4"

# RPC Traversal
futures = "0.3"
ethers-providers = "2.0"
ethers-core = "2.0"
tokio = { version = "1.34", features = [
    "rt-multi-thread",
    "macros",
] }
